#!/usr/bin/env bash
POKY_SDK_PATH='/home/build/opt/poky'
CURRENT_DIR="$(dirname $(readlink -f $0))"
LAYERS_DIR="layers"
RECIPES_IK_DIR="$LAYERS_DIR/custom/meta-ik/recipes-ik"

if [ 2 -ne $# ]; then
    echo 'Usage: preBuild [sumo | zeus | dunfell] build-dir-path'
#    cd "${RECIPES_IK_DIR}"
#    for item in *; do
#        [ -d $item ] && echo "Branch: $item"
#    done
    exit 0
fi

BRANCH=${1}
if [ 'sumo' = ${BRANCH} ]; then
    POKY_SDK_PATH="${POKY_SDK_PATH}/2.5.3"
elif [ 'zeus'  = ${BRANCH} ]; then
    POKY_SDK_PATH="${POKY_SDK_PATH}/3.0"
elif [ 'dunfell'  = ${BRANCH} ]; then
    POKY_SDK_PATH="${POKY_SDK_PATH}/3.1"
fi
RECIPES_IK_DIR="${RECIPES_IK_DIR}/${BRANCH}/images"

BUILD_DIR="${CURRENT_DIR}/${2}"
cd "${LAYERS_DIR}"
source syncAll.sh ${BRANCH}

cd "${CURRENT_DIR}"
echo "--- Prepare build workspace ---"
echo "source $POKY_SDK_PATH/environment-setup-x86_64-pokysdk-linux"
echo "source /home/build/layers/internet/poky/oe-init-build-env ${2}"

cd "${RECIPES_IK_DIR}"
for layers in *; do
    if [ -f $layers ]; then
        prefix=${layers%%.*}
        suffix=${layers:${#prefix}}
        if [[ ".bblayers.conf" == ${suffix} ]]; then
            echo ""
            echo "+++ Layers: ${prefix} +++"
            for recipe in *; do
                if [[ -f $recipe ]] && [[ ${recipe:0:${#prefix}} == ${prefix} ]]; then
                    name=${recipe%%.*}
                    extension=${recipe:${#name}}
                    if [[ '.bb' == $extension  ]]; then
                        echo ""
                        echo "--- --- Configuration: ${name} --- ---"
                        echo "cp -fv ${PWD}/${layers} ${BUILD_DIR}/conf/bblayers.conf"
                        echo "cp -fv ${PWD}/${name}.local.conf ${BUILD_DIR}/conf/local.conf"
                        echo "bitbake -c build virtual/kernel"
                        echo "bitbake $name && bitbake $name -c populate_sdk"
                    fi
                fi
            done
            
        fi
    fi
done
